version: '3'
services:
  vertica:
    image: jbfavre/vertica:latest 
    ports:
      - 5433:5433
  
  tests:
    build:
      context: .
    depends_on:
      - vertica
    environment:
      - VERTICA_HOST=vertica
    entrypoint: >
        sh -c "pytest . -vvs --durations=0"