version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=db_test
    ports:
      - 5432:5432
    volumes:
      - ./db_test.sql:/docker-entrypoint-initdb.d/db_test.sql