name: UGC app CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.(7/8/9)
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Create reports dir
        run: |
          mkdir -p reports/mypy_reports/api
          mkdir -p reports/mypy_reports/etl
          mkdir -p reports/flake8_reports/api
          mkdir -p reports/flake8_reports/etl
      - name: Install MyPy & flake8
        run: |
          pip3 install lxml==4.9.1
          pip3 install mypy==0.971
          pip3 install wemake-python-styleguide==0.16.1
          pip3 install flake8-html
      - name: Run mypy
        run: |
          mypy api --ignore-missing-imports --html-report reports/mypy_reports/api/
          mypy etl --ignore-missing-imports --html-report reports/mypy_reports/etl/
      - name: Run flake8
        run: |
          flake8 api/ --ignore=WPS,B008 --show-source
          flake8 etl/ --ignore=WPS,B008 --show-source
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: UGC CI report
          path: reports/
          if-no-files-found: warn
          retention-days: 0 
          

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
